# Generated by Django 4.2.1 on 2023-07-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("instructor", "Instructor"),
                    ("admin", "Admin"),
                    ("student", "Student"),
                ],
                default="student",
                max_length=100,
            ),
        ),
    ]
