# Generated by Django 4.2.1 on 2023-07-27 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("for_review", "For Review"),
                    ("active", "Active"),
                ],
                default="for_review",
                max_length=100,
            ),
        ),
    ]
